freebsd_instance:
  image_family: freebsd-12-2-snap
  cpu: 8
  memory: 16G

env:
  CIRRUS_CLONE_DEPTH: 1

doc_task:
  timeout_in: 120m
  install_script:
    - pkg install -y gohugo python3 git-lite rubygem-asciidoctor rubygem-rouge
  test_script:
    - cd documentation && make move-shared && make generate -v

www_task:
  timeout_in: 120m
  install_script:
    - pkg install -y gohugo python3 git-lite rubygem-asciidoctor rubygem-rouge
  test_script:
    - cd website && make move-shared && make generate -v
